/** Copyright (c) 2026 Ilya Zverev. <ilya@zverev.info>

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
of the Software, and to permit persons to whom the Software is furnished to do
so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

*/

syntax = "proto3";

// Same package as for GTFS Proto.
package gtfs;

// File structure: magic bytes 'GTB\n', blocks, Footer message,
// 2-byte big-endian length of the footer (a hint taken from ORC format).
message Footer {
  // Version of the schema.
  uint32 version = 1;

  // Date when the original GTFS feed was built, in YYMMDD format (240319).
  // Alternatively, a release number for the feed. The only requirement
  // is that newer feeds should have this number greater than the older.
  uint32 date = 2;

  // In case of errors, this would be the reference GTFS feed, zip file itself.
  // Please link to specific builds if possible, e.g. "20240319", not "latest".
  string original_url = 3;

  // If true, all blocks are compressed with Zstandard by default.
  // Including all metadata blocks.
  bool compressed = 4;

  // The rest of the file is blocks in random order.
  repeated BlockMetadata blocks = 6;
}

message BlockMetadata {
  // Type of the block.
  Block block = 1;

  // Offset of the first byte in the file.
  uint64 offset = 2;

  // Length of the metadata message.
  uint32 length = 3;

  // Whether the metadata message is compressed.
  bool compressed = 4;
}

enum Block {
  B_UNKNOWN = 0;
  B_STOPS = 1;
  B_CALENDAR = 2;
  B_ROUTES = 3;
  B_SHAPES = 4; // optional
  B_LOOKUP = 5; // optional
  B_AGENCIES = 6;
}


// Included here because it's the source for time zones and URLs.
// Enumerated from zero, like array indices.
message Agencies {
  repeated Agency agencies = 1;
  repeated string ticket_info = 2;
  repeated Realtime realtime = 3;
}

message Agency {
  string name = 1;
  string url = 2;
  string timezone = 3;
  string lang = 4;
  string phone = 5;
  string fare_url = 6;
  string email = 7;
  // index + 1 from Agencies.ticket_info
  uint32 ticket_info = 8;
  // index + 1 from Agencies.realtime
  uint32 realtime = 9;
}

message Realtime {
  RealtimeType type = 1;
  string url = 2;
}

enum RealtimeType {
  RT_UNKNOWN = 0;
  RT_GTFS = 1; // GTFS-RT
}


// This is the simplest block. Shape messages immediately follow the
// metadata block and ordered by their ids.
message ShapeMetadata {
  // Shapes can be grouped into chunks to compress them more effectively.
  // All chunks are of the same size. Should be at least 1.
  uint32 chunk_size = 1;

  // Sizes in bytes for each consequtive chunk. Note that those are compressed
  // sizes. You can get an offset by adding this block offset, this block length,
  // and all chunk length from 0 up until the preceding one.
  repeated uint32 chunk_lengths = 2;
}

// Sequence of shapes in a chunk. Follows ShapeMetadata, not included in it.
message ShapeChunk {
  repeated Shape shapes = 1;
}

// A single shape. Its identifier is its number in file, starting from 1.
message Shape {
  // Numbers multiplied by 100000 (1e5) and rounded.
  // Mind the accumulated rounding error!
  // Each number is the difference with the last.
  repeated sint32 longitudes = 1;
  repeated sint32 latitudes = 2;
}


// Stops are split into chunks for 24-bit geohashes to speed up retrieval.
// For stops within stations, the station geohash is used for chunking.
message StopMetadata {
  uint32 geohash_xor = 1;
  // Delta-coded geohashes. Should be XOR-ed with geohash_xor.
  repeated uint32 geohashes = 2;
  // In bytes. Negative if not compressed (but everything else is).
  repeated sint32 chunk_lengths = 3;
  // This field helps look up stop_id → chunk + index in the chunk.
  repeated uint32 chunk_stop_counts = 4;
  // If false, is_station and parent_id in chunks are skipped.
  bool has_stations = 5;
}

// Column-oriented set of stops. Which means, it's a set
// of packed column values. E.g. the code field contains strings
// for every stop in the chunk.
//
// Even if packing everything in a single field, having lengths in those
// would mean adding 30 bytes to every stop,
// which might mean over 3 MB for a feed. Hence we process the binary
// data directly. This message is not used, but demonstrates an order and
// types of fields.
message StopsChunk {
  string gtfs_id = 1; // 1-byte length and utf-8 string
  string code = 2; // same
  string name = 3; // same
  string desc = 4; // same
  sint32 lat = 5; // multiplied by 100000 (1e5), delta-coded
  sint32 lon = 6; // same
  // This field is bit-packed (2 bits each, 0b00112233 for 0,1,2,3).
  Accessibility wheelchair = 7;
  repeated uint32 route_ids = 8; // uint32 length, then uints delta-coded

  // Those two are skipped if has_stations is false.
  bool is_station = 9; // we skip all exit/node/boarding stops, bit-packed
  uint32 parent_id = 10; // stop position inside the chunk + 1, RLE-encoded

  uint32 geohash = 30; // not included, for sorting purposes.
}

enum Accessibility {
  A_UNKNOWN = 0;
  A_SOME = 1;
  A_NO = 2;
}


// Unlike other blocks, this one is completely contained in the metadata.
message LookupMetadata {
  StopLookup stop_by_name = 1;
  StopLookup stop_by_gtfs_id = 2;
  StopLookup route_by_gtfs_id = 3;
}


// Encodes a radix trie structure.
message StopLookup {
  // Edges reference this blob.
  bytes string_blob = 1;
  // Nodes reference stop ids, which are ordered for convenient lookup.
  repeated uint32 stop_ids = 2;
  // Nodes in the graph, split into columns to compress better.
  repeated uint32 node_edge_offset = 3; // delta-coded
  repeated uint32 node_edge_count = 4;
  repeated uint32 node_stop_offset = 5; // delta-coded
  repeated uint32 node_stop_count = 6;
  // Edges in the graph.
  repeated uint32 edge_label_offset = 7;
  repeated uint32 edge_label_length = 8;
  repeated uint32 edge_node_index = 9;
}


message CalendarMetadata {
  // A number as YYMMDD: e.g. 240821.
  // The year is ±5 years from today, error otherwise.
  // All service dates use offsets in days from it.
  uint32 base_date = 1;

  // Start dates for every service. First is offset from base_date,
  // second and others are deltas from previous. Services should be sorted
  // by start_date, so every number in this list is positive.
  repeated uint32 start_dates = 2;

  // End dates for every service, difference with start_date.
  repeated uint32 end_dates = 3;

  // Bit-encoded weekdays for every service, sequentially.
  // One byte is one service. Zeroes for non-weekday-based services.
  // Bit 0 is Monday, 6 is Sunday: 0b0SSFTWTM. 0x60 is weekends.
  repeated uint32 weekdays = 4;

  // This message is followed by a series of CalendarMonth chunks.
  // Despite the name, those can contain arbitrary number of days.
  // The first "month" starts at the base_date and goes on incrementally.
  uint32 days_in_month = 5;

  // Compressed length in bytes for each consequtive "month" chunk.
  // Can be zero for some months. Negative if not compressed.
  // We package at most a year of dates.
  repeated sint32 month_lengths = 6;
}

// These follow the CalendarMetadata, not attached to messages.
message CalendarMonth {
  // Delta coded, first date is offset from the months start.
  // Default is [0, 1, 1, 1, ...]. Cut on the last non-default value.
  repeated uint32 date_offsets = 1;
  repeated CalendarDate dates = 2;
}

message CalendarDate {
  // List of service ids incrementally, delta-coded.
  repeated uint32 included_in = 1;

  // List of serivce ids incrementally, delta-coded.
  repeated uint32 exception_in = 2;
}


message RouteMetadata {
  // Compressed length in bytes for each route. Their identifiers
  // are indices in this list.
  repeated uint32 route_lengths = 1;

  // Those two determine whether we skip "wheelchair" and "bikes" field from trips.
  bool has_wheelchair_info = 2;
  bool has_bike_info = 3;
}

// These follow the RouteMetadata, not attached to any message.
message Route {
  uint32 agency_id = 1;
  string gtfs_id = 2;
  RouteType type = 3;
  string short_name = 4;
  string long_name = 5;
  string desc = 6;
  uint32 color = 7; // note: black (0x000000) and white (0xffffff) are swapped!
  uint32 text_color = 8;
  bool has_frequencies = 9; // whether frequencies in trips are present

  // No sorting order.
  repeated Itinerary itineraries = 10;
  // Headsign dictionary, referenced from itineraries (may contain an empty one).
  repeated string headsigns = 11;
}

message Itinerary {
  uint32 shape_id = 1; // plus one, so zero means no shape
  repeated uint32 stop_ids = 2;
  bytes headsigns = 3; // references, uints RLE
  bytes pickup_types = 4; // bit-packed (2 bit each). Skipped if all but last are zeroes.
  bytes dropoff_types = 5; // same, also skipped if all but first are zeroes.
  bool opposite_direction = 6;

  // The most common deltas between stop departures for trips.
  // Granularity is 5 seconds, rounded down.
  repeated uint32 departure_deltas = 7;

  bytes service_ids = 8; // instead of lengths we pack the single remaning mandatory field, uint RLE
  bytes trips = 9; // no point in reading the chunk separately
}

// Column-oriented set of trips following the Route message.
// As for StopsChunk, does not appear as is, but lists fields
// and their types for unpacking.
// Trips are ordered by the first departure.
message TripsChunk {
  // (hours * 720) + (minutes * 12) + (seconds / 5), rounded down. Delta-coded.
  // First because we want to filter trips by first stop-last stop times.
  uint32 first_stop_departure = 1;

  // Differences from itinerary.depature_deltas, RLE-packed. Granularity is 5 seconds.
  // Transposed: first all trips for stop 1, then for stop 2 etc etc.
  // Count is (number of trips) × (number of stops - 1)
  // There are no missing values: we pre-calculate missing departure times.
  // Mind the accumulated rounding error!
  // The entire list is delta-coded.
  repeated sint32 departure_deltas = 2;

  // (we skip arrivals because they matter less)

  // Not a simple length + string: first byte is length when < 0x80.
  // When 7 bit is set, it has a common prefix length with the previous,
  // and the suffix length is in the next byte. The first can be of 255 length.
  string gtfs_id = 3;

  // schedule-based: whether we can trust every timestamp for departures/arrivals.
  // frequency-based: whether the intervals are exact. Bit-packed.
  bool approximate = 4;

  // When Route.has_frequencies is true, those two are present.
  // Start time is in first_stop_departure. Granularity is 5 seconds.
  // Rounding down for start and up for end.
  uint32 end_time = 5; // delta from first_stop_departures, 0 if not freq-based.
  // Here, granularity is 1 second, like in GTFS. No point in saving a byte.
  uint32 interval = 6;

  // Present only when RouteMetadata.has_wheelchair/bikes are true
  Accessibility wheelchair = 7; // bit-packed (2 bits each)
  Accessibility bikes = 8; // same
}

enum PickupDropoff {
  PD_YES = 0; // the default, for unspecified
  PD_NO = 1;
  PD_PHONE_AGENCY = 2;
  PD_TELL_DRIVER = 3;
}

// See also https://developers.google.com/transit/gtfs/reference/extended-route-types
enum RouteType {
  T_BUS = 0; // 3 and all 7xx (buses are the default to keep space)
  T_TRAM = 1; // 0 and all 9xx
  T_SUBWAY = 2; // 1 and 401-402
  T_RAIL = 3; // 2 and all 1xx
  T_FERRY = 4; // 4 and 1200
  T_CABLE_TRAM = 5; // 5 and maybe 1302 but not sure
  T_AERIAL = 6; // 6 and 13xx
  T_FUNICULAR = 7; // 7 and 1400
  T_COMMUNAL_TAXI = 9; // 1501
  T_COACH = 10; // all 200-209
  T_TROLLEYBUS = 11; // 11 and 800
  T_MONORAIL = 12; // 12 and 405

  T_URBAN_RAIL = 21; // 400, 403-404
  T_WATER = 22; // 1000
  T_AIR = 23; // 1100
  T_TAXI = 24; // all 15xx except 1501
  T_MISC = 25; // 17xx
}
